docs: updates to make styling consistent
asyncapi/design-system pull request #36
Opened 2022-05-25 10:25 UTC by naman-tiwari

- Enhanced the readme file by adding emojis.

2022-05-25 11:47 UTC, magicmatatjahu requested changes
Please try to make good indents for code:

```
  ```sh
  npm install
  ```
```

2022-05-25 11:47 UTC, magicmatatjahu commented on README.md
> +  npm install --save-dev
Try to make good indents by adding two spaces before "`" signs and also change

```
npm install --save-dev
```

to the

```
npm install
```

2022-05-25 15:25 UTC, naman-tiwari commented
I have added indents before npm commands and changed `npm install --save-dev` to `npm install`

2022-05-26 20:01 UTC, mcturco commented
I think my suggestions that I wrote in the other PR got lost. I think it was just suggesting to re-write some of the wording so it reads better. Are you able to see my review in the other PR and apply the changes here, @naman-tiwari?

2022-05-27 01:44 UTC, naman-tiwari commented
> I think my suggestions that I wrote in the other PR got lost. I think it was just suggesting to re-write some of the wording so it reads better. Are you able to see my review in the other PR and apply the changes here, @naman-tiwari?

I will resolve the requested changes by today @mcturco .

2022-05-27 09:19 UTC, naman-tiwari reviewed
The requested changes by @mcturco have been addressed.

2022-05-27 13:11 UTC, magicmatatjahu requested changes

2022-05-27 13:11 UTC, magicmatatjahu commented on README.md
> +- By default, this will launch your local Storybook environment on port '6006'.
```suggestion
- By default, this will launch your local Storybook environment on port `6006`.
```

2022-05-27 13:11 UTC, magicmatatjahu commented on README.md
> +- Now that you've installed all of the 'node modules' in your project, you can launch the Storybook environment. To get started, type the command below:
```suggestion
- Now that you've installed all of the `node modules` in your project, you can launch the Storybook environment. To get started, type the command below:
```

2022-05-31 13:50 UTC, mcturco approved these changes
LGTM! 🚢

2022-07-25 10:33 UTC, magicmatatjahu commented
@naman-tiwari Sorry for such a delay. As I see in the netlify logs you should remove `export` script from `build` script and we can merge it :)

2022-11-28 05:33 UTC, fmvilas approved these changes

2022-11-28 05:42 UTC, fmvilas commented
/rtm

2022-11-28 05:42 UTC, merged

2022-11-28 05:42 UTC, fmvilas commented
I'm merging as the problem is not related to this PR anyway.

2022-11-28 05:43 UTC, fmvilas commented
Sorry it took that long @naman-tiwari. I just noticed it because the bot added the stale label.